"""Conservative layout persistence for the live Excalidraw viewer."""

import json
from pathlib import Path
from typing import Any, Dict, Iterable, Set

from ..excalidraw.positions import extract_positions_from_elements, merge_positions


def save_viewer_layout(
    folder: Path,
    elements: Iterable[Dict[str, Any]],
) -> Dict[str, Dict[str, Any]]:
    """Persist layout fields for generated nodes from a viewer scene update."""
    scene = load_scene(folder / "output.excalidraw")
    known_node_ids = get_known_node_ids(scene.get("elements", []))
    positions = extract_positions_from_elements(
        elements,
        known_node_ids=known_node_ids,
        baseline_elements=scene.get("elements", []),
    )
    merge_positions(folder / "positions.json", positions)
    return positions


def load_scene(path: Path) -> Dict[str, Any]:
    """Load the generated Excalidraw scene."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, dict) else {}


def get_known_node_ids(elements: Iterable[Dict[str, Any]]) -> Set[str]:
    """Return node IDs currently generated by excali-builder."""
    node_ids: Set[str] = set()
    for element in elements:
        custom_data = element.get("customData")
        if not isinstance(custom_data, dict):
            continue
        node_id = custom_data.get("node_id")
        if isinstance(node_id, str) and node_id:
            node_ids.add(node_id)
    return node_ids
